# Generated by Django 6.0.3 on 2026-03-14 09:11

import backend.utils.imagekit_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=backend.utils.imagekit_storage.ImageKitStorage('/media/'), upload_to=''),
        ),
    ]
