# Generated by Django 6.0.3 on 2026-03-14 10:16

import backend.utils.imagekit_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=backend.utils.imagekit_storage.ImageKitStorage(), upload_to=''),
        ),
    ]
